mf6:
  workspace: "../../MF6/nm/mfnm"
  dll: "~/usr/local/src/modflow6/bin/libmf6.so"
  start_date: "1990-01-01"
  model_name: "mfnm"

vic:
  dir: "../../VIC"                # VIC top-level dir
  exe: "~/usr/local/src/VIC/vic/drivers/image/vic_image.exe"
  global_param: "global_param_nc4.txt"   # relative to vic.dir
  outputs_dir: "outputs"                 # relative to vic.dir
  exchange_dir: "exchange_data"          # relative to vic.dir (or wherever you want)
  params_file: "nc4_params.nc"           # relative to vic.dir
  wbal_var: "OUT_BASEFLOW"
  init_moist_layer: 2

coupling:
  table_csv: "../vic_mf6_exchange_rch.csv"
  start_date: "1990-01-01"
  end_date: "1990-12-31"
  vic_grid_shape: [227, 212]

logging:
  file: "./logs/stdout.log"
  level: "INFO"
